language: python
dist: xenial
services:
  - xvfb
python:
  - "3.7"
addons:
  chrome: beta
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
install:
  - pip install --upgrade -r dev-requirements.txt
  - pip install --upgrade -r requirements.txt
script: INTRAVIS=TRUE pytest