dist: trusty
language: python
sudo: required
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
python:
  - "3.6"
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest pytest-asyncio psutil grappa vibora
script: INTRAVIS=TRUE pytest