dist: xenial
language: python
python:
  - "3.6"
addons:
  chrome: beta
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest pytest-asyncio psutil grappa vibora
script: INTRAVIS=TRUE pytest